server.port=8080
spring.application.name=api-gateway


management.endpoints.web.exposure.include=health,info

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins=http://localhost:8082
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allow-credentials=true
spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true