

server.port=8080
spring.application.name=api-gateway
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/medilabo


spring.cloud.gateway.routes[0].id=patient-service
spring.cloud.gateway.routes[0].uri=http://patient-service:8084
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/patients/**

spring.cloud.gateway.routes[0].filters[0]=RemoveRequestHeader=Authorization

spring.cloud.gateway.routes[1].id=history-service
spring.cloud.gateway.routes[1].uri=http://history-service:8083
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/notes/**
spring.cloud.gateway.routes[1].filters[0]=RemoveRequestHeader=Authorization

spring.cloud.gateway.routes[2].id=assessment-service
spring.cloud.gateway.routes[2].uri=http://assessment-service:8085
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/assessments/**
spring.cloud.gateway.routes[2].filters[0]=RemoveRequestHeader=Authorization


management.endpoints.web.exposure.include=health,info,prometheus

# CORS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins=http://localhost:8082
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allow-credentials=true
spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true

logging.level.org.springframework.security.oauth2.client=DEBUG
logging.level.org.springframework.security.oauth2.core=DEBUG
