server.port=8085
spring.application.name=assessment-service


services.patient.base-url=http://patient-service:8084
services.history.base-url=http://history-service:8083

management.endpoints.web.exposure.include=health,info,prometheus