

server.port=8083
spring.application.name=history-service

spring.data.mongodb.uri=mongodb://mongo:27017/medilabo_history
spring.data.mongodb.auto-index-creation=true

spring.jackson.serialization.write-dates-as-timestamps=false
management.endpoints.web.exposure.include=health,info,prometheus