server.port=8082
spring.application.name=front-app

management.endpoints.web.exposure.include=health,info

# En local, le gateway est sur localhost:8080
medilabo.gateway.base-url=http://localhost:8080