server.port=8082
spring.application.name=front-app

spring.security.oauth2.client.registration.keycloak.client-id=front-app
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email
spring.security.oauth2.client.registration.keycloak.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.keycloak.client-authentication-method=client_secret_basic
spring.security.oauth2.client.registration.keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET}

# Navigateur -> Keycloak (doit être accessible depuis la machine hôte)
spring.security.oauth2.client.provider.keycloak.authorization-uri=http://localhost:8080/realms/medilabo/protocol/openid-connect/auth
spring.security.oauth2.client.provider.keycloak.jwk-set-uri=http://localhost:8080/realms/medilabo/protocol/openid-connect/certs
spring.security.oauth2.client.provider.keycloak.user-info-uri=http://localhost:8080/realms/medilabo/protocol/openid-connect/userinfo

# Back-channel (front-app -> Keycloak via le réseau Docker)
spring.security.oauth2.client.provider.keycloak.token-uri=http://keycloak:8080/realms/medilabo/protocol/openid-connect/token

medilabo.gateway.base-url=http://api-gateway:8080
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false


logging.level.org.springframework.security.oauth2.client=DEBUG
logging.level.org.springframework.security.oauth2.core=DEBUG



