server.port=8084
spring.application.name=patient-service


spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.open-in-view=false

spring.flyway.baseline-on-migrate=true

management.endpoints.web.exposure.include=health,info,prometheus
