

server.port=8084
spring.application.name=patient-service

spring.datasource.url=jdbc:mysql://mysql:3306/medilabo_patients?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=rootroot
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.open-in-view=false


spring.jpa.properties.hibernate.type.preferred_enum_type=STRING

spring.flyway.baseline-on-migrate=true
management.endpoints.web.exposure.include=health,info,prometheus


spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration